#
# Copyright (c) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause
#
# VRK160 "rfloop" overlay -- minimal RF loopback.
#
# DAC tile 0 slice 0 emits a tone, the XM855 daughterboard loops it back
# externally, ADC tile 3 slice 0 receives it, and a burst of samples is
# captured to DDR over DMA. Tile choice, sample rate and reference clock
# follow AMD's ftloop reference design for this board.
#
# The tone is generated by the converter's own fine mixer NCO from a DC
# input, not by a DDS in the PL -- see hdl/dac_tone_src.v. Set the frequency
# from Python with xvrfdc, which is the same call the QICK port needs.
#
# Requires the Versal RF Data Converter IP, which is not part of Vivado:
# point PYNQ_VRFDC_IP_REPO at the extracted VRFDC_Vivado_IP_Repo directory.

set design_name "rfloop"
set script_dir  [file dirname [file normalize [info script]]]

# Step 0: user IP repository for vrf_data_converter
if {![info exists ::env(PYNQ_VRFDC_IP_REPO)]} {
    puts "ERROR: PYNQ_VRFDC_IP_REPO is not set."
    puts "       The Versal RF Data Converter IP does not ship with Vivado."
    puts "       Download the VRFDC Vivado IP repo from AMD and set, e.g.:"
    puts "         export PYNQ_VRFDC_IP_REPO=/path/to/VRFDC_Vivado_IP_Repo_v1_3_<id>"
    exit 1
}
set vrfdc_ip_repo [file normalize $::env(PYNQ_VRFDC_IP_REPO)]
if {![file isdirectory $vrfdc_ip_repo]} {
    puts "ERROR: PYNQ_VRFDC_IP_REPO is not a directory: $vrfdc_ip_repo"
    exit 1
}

# Step 1: Source the golden reference design
source [file join $script_dir ../golden/golden_ref.tcl]

# The golden created the project; add the IP repo to it and re-scan.
set_property ip_repo_paths [concat [get_property ip_repo_paths [current_project]] \
                                   $vrfdc_ip_repo] [current_project]
update_ip_catalog -rebuild

if {[llength [get_ipdefs -all xilinx.com:ip:vrf_data_converter:*]] == 0} {
    puts "ERROR: vrf_data_converter not found after adding $vrfdc_ip_repo"
    exit 1
}

# Step 2: Remove the PL tie-offs this overlay replaces.
#
# pl_tieoff_pb and pl_tieoff_dma1 are deliberately kept: this overlay has no
# use for the push buttons (whose cell the golden owns because their pins
# share bank silicon with LPDDR5) and needs only one of the two PL NoC
# ports. Leaving their stand-ins in place keeps the design valid without
# adding logic that does nothing.
delete_bd_objs [get_bd_cells pl_tieoff_m00axi]
delete_bd_objs [get_bd_cells pl_tieoff_dma0]
foreach irq_pin [get_bd_pins ps_wizard_0/pl_ps_irq*] {
    set net [get_bd_nets -of_objects $irq_pin -quiet]
    if {$net ne ""} { delete_bd_objs $net }
}
delete_bd_objs [get_bd_cells pl_tieoff_irq]

# Step 3: RTL sources for the tone source and the capture gate, plus the
# reference-clock constraints for the converter tiles.
add_files -norecurse [glob [file join $script_dir hdl *.v]]
add_files -fileset constrs_1 -norecurse [file join $script_dir vrk160_rf_clocks.xdc]
update_compile_order -fileset sources_1

# Step 4: The converter.
#
# DAC0/ADC3 at 7.86432 GSps from a 491.52 MHz reference with the internal
# PLL, interpolation and decimation by 2, 16-bit data. This is AMD's ftloop
# configuration for VRK160 verbatim; every parameter name below exists
# unchanged in IP v1.2 and v1.3.
set vrfdc [create_bd_cell -type ip -vlnv xilinx.com:ip:vrf_data_converter vrf_data_converter_0]
set_property -dict [list \
    CONFIG.ADC3_Outclk_Freq         {491.520} \
    CONFIG.ADC3_PLL_Enable          {true} \
    CONFIG.ADC3_Refclk_Freq         {491.520} \
    CONFIG.ADC3_Sampling_Rate       {7.864320} \
    CONFIG.ADC_Coarse_Mixer_Freq30  {1} \
    CONFIG.ADC_Data_Type30          {1} \
    CONFIG.ADC_Data_Width30         {16} \
    CONFIG.ADC_Decimation_Mode30    {2} \
    CONFIG.ADC_Dither30             {false} \
    CONFIG.ADC_Mode30               {1} \
    CONFIG.ADC_Slice00_Enable       {false} \
    CONFIG.ADC_Slice10_Enable       {false} \
    CONFIG.ADC_Slice20_Enable       {false} \
    CONFIG.ADC_Slice30_Enable       {true} \
    CONFIG.ADC_Sysref_Source        {1} \
    CONFIG.DAC0_Outclk_Freq         {491.520} \
    CONFIG.DAC0_PLL_Enable          {true} \
    CONFIG.DAC0_Refclk_Freq         {491.520} \
    CONFIG.DAC0_Sampling_Rate       {7.864320} \
    CONFIG.DAC_Coarse_Mixer_Freq00  {2} \
    CONFIG.DAC_Data_Type00          {0} \
    CONFIG.DAC_Data_Width00         {16} \
    CONFIG.DAC_Interpolation_Mode00 {2} \
    CONFIG.DAC_Mixer_Mode00         {0} \
    CONFIG.DAC_Mixer_Type00         {1} \
    CONFIG.DAC_Mode00               {1} \
    CONFIG.DAC_RTS                  {false} \
    CONFIG.DAC_Slice00_Enable       {true} \
    CONFIG.DAC_Slice10_Enable       {false} \
    CONFIG.DAC_Slice20_Enable       {false} \
    CONFIG.DAC_Slice30_Enable       {false} \
] $vrfdc

# Step 5: AXIS clock domain.
#
# clk_dac0 is an output of the converter at 491.52 MHz. It is regenerated
# through a clocking wizard onto a BUFG, exactly as the ftloop reference
# does, and that is the clock for everything on the converter side.
set clk_rf [create_bd_cell -type ip -vlnv xilinx.com:ip:clkx5_wiz clk_rf_wiz]
set_property -dict [list \
    CONFIG.CLKOUT_REQUESTED_OUT_FREQUENCY {491.520,100.000,100.000,100.000,100.000,100.000,100.000} \
    CONFIG.CLKOUT_USED {true,false,false,false,false,false,false} \
    CONFIG.PRIM_IN_FREQ {491.520} \
    CONFIG.PRIM_SOURCE {No_buffer} \
    CONFIG.RESET_TYPE {ACTIVE_LOW} \
    CONFIG.USE_LOCKED {true} \
    CONFIG.USE_RESET {true} \
] $clk_rf

set rst_rf [create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset rst_rf]

# Step 6: Datapath
set tone_src [create_bd_cell -type module -reference dac_tone_src dac_tone_src_0]
set cap_gate [create_bd_cell -type module -reference adc_capture_gate adc_capture_gate_0]

# Async FIFO: absorbs the burst at 491.52 MHz and hands it to the 100 MHz
# DMA domain. Its depth is what bounds the capture -- see the gate's header.
set cap_fifo [create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo cap_fifo]
set_property -dict [list \
    CONFIG.FIFO_DEPTH {8192} \
    CONFIG.FIFO_MEMORY_TYPE {ultra} \
    CONFIG.TDATA_NUM_BYTES {32} \
    CONFIG.HAS_TLAST {1} \
    CONFIG.IS_ACLK_ASYNC {1} \
] $cap_fifo

# 256 -> 128 bits: the PL NoC slave ports are 128-bit and defined by the
# golden, so the DMA cannot be widened to match the converter.
set dwidth [create_bd_cell -type ip -vlnv xilinx.com:ip:axis_dwidth_converter cap_dwidth]
set_property -dict [list \
    CONFIG.S_TDATA_NUM_BYTES {32} \
    CONFIG.M_TDATA_NUM_BYTES {16} \
    CONFIG.HAS_TLAST {1} \
] $dwidth

# S2MM only: nothing streams towards the DAC over DMA.
set axi_dma [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_dma:7.1 axi_dma_0]
set_property -dict [list \
    CONFIG.c_include_sg {0} \
    CONFIG.c_include_mm2s {0} \
    CONFIG.c_sg_include_stscntrl_strm {0} \
    CONFIG.c_addr_width {64} \
    CONFIG.c_m_axi_s2mm_data_width {128} \
    CONFIG.c_s_axis_s2mm_tdata_width {128} \
    CONFIG.c_s2mm_burst_size {256} \
] $axi_dma

# Channel 1 out = arm, channel 2 in = busy.
set gpio_cap [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 axi_gpio_capture]
set_property -dict [list \
    CONFIG.C_IS_DUAL {1} \
    CONFIG.C_GPIO_WIDTH {1}  CONFIG.C_ALL_OUTPUTS {1} \
    CONFIG.C_GPIO2_WIDTH {1} CONFIG.C_ALL_INPUTS_2 {1} \
    CONFIG.C_INTERRUPT_PRESENT {0} \
] $gpio_cap

# Step 7: Control path -- SmartConnect fanning FPD_AXI_PL out to 3 slaves.
# Cells only here; every interface is connected in step 11, after the clocks.
set axi_smc [create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect:1.0 axi_smc]
# One clock domain: FPD_AXI_PL and all three AXI-Lite slaves are on
# pl0_ref_clk. The converter's register interface is there too -- only its
# data streams live in the 491.52 MHz domain.
set_property -dict [list CONFIG.NUM_MI {3} CONFIG.NUM_SI {1} CONFIG.NUM_CLKS {1}] $axi_smc


# Step 8: External RF ports (declared here, connected in step 11).
#
# No LOC constraints are needed: the converter's analog and reference-clock
# pins are fixed by the silicon once the tiles are chosen, which is why the
# ftloop XDC only declares the two input clocks. That matters here because
# this board's golden deliberately does not use the Vivado board preset.
create_bd_intf_port -mode Slave  -vlnv xilinx.com:interface:diff_clock_rtl:1.0 dac0_clk
create_bd_intf_port -mode Slave  -vlnv xilinx.com:interface:diff_clock_rtl:1.0 adc3_clk
create_bd_intf_port -mode Slave  -vlnv xilinx.com:display_vrf_data_converter:diff_pins_rtl:1.0 sysref_dac_in
create_bd_intf_port -mode Master -vlnv xilinx.com:interface:diff_analog_io_rtl:1.0 vout00
create_bd_intf_port -mode Slave  -vlnv xilinx.com:interface:diff_analog_io_rtl:1.0 vin30


# Step 9: Clocks
connect_bd_net [get_bd_pins $vrfdc/clk_dac0] [get_bd_pins clk_rf_wiz/clk_in1]

set rf_clk [get_bd_pins clk_rf_wiz/clk_out1]
connect_bd_net $rf_clk \
    [get_bd_pins rst_rf/slowest_sync_clk] \
    [get_bd_pins $vrfdc/s0_axis_aclk] \
    [get_bd_pins $vrfdc/m3_axis_aclk] \
    [get_bd_pins dac_tone_src_0/aclk] \
    [get_bd_pins adc_capture_gate_0/aclk] \
    [get_bd_pins cap_fifo/s_axis_aclk]

# pl0_ref_clk (100 MHz) is the control and DMA domain.
connect_bd_net [get_bd_pins ps_wizard_0/pl0_ref_clk] \
    [get_bd_pins axi_smc/aclk] \
    [get_bd_pins $vrfdc/s_axi_aclk] \
    [get_bd_pins axi_dma_0/s_axi_lite_aclk] \
    [get_bd_pins axi_dma_0/m_axi_s2mm_aclk] \
    [get_bd_pins axi_gpio_capture/s_axi_aclk] \
    [get_bd_pins cap_fifo/m_axis_aclk] \
    [get_bd_pins cap_dwidth/aclk]

# Step 10: Resets
connect_bd_net [get_bd_pins rst_pl0/peripheral_aresetn] \
    [get_bd_pins clk_rf_wiz/resetn] \
    [get_bd_pins rst_rf/ext_reset_in] \
    [get_bd_pins axi_smc/aresetn] \
    [get_bd_pins $vrfdc/s_axi_aresetn] \
    [get_bd_pins axi_dma_0/axi_resetn] \
    [get_bd_pins axi_gpio_capture/s_axi_aresetn] \
    [get_bd_pins cap_fifo/m_axis_aresetn] \
    [get_bd_pins cap_dwidth/aresetn]

connect_bd_net [get_bd_pins clk_rf_wiz/locked] [get_bd_pins rst_rf/dcm_locked]

connect_bd_net [get_bd_pins rst_rf/peripheral_aresetn] \
    [get_bd_pins $vrfdc/s0_axis_aresetn] \
    [get_bd_pins $vrfdc/m3_axis_aresetn] \
    [get_bd_pins dac_tone_src_0/aresetn] \
    [get_bd_pins adc_capture_gate_0/aresetn] \
    [get_bd_pins cap_fifo/s_axis_aresetn]

# Step 11: All interface connections.
#
# Deliberately after the clocks. IPI propagates FREQ_HZ and
# CLK_DOMAIN along an interface at the moment it is connected, so wiring the
# streams first leaves cap_fifo/M_AXIS still advertising its input clock and
# validation fails against cap_dwidth/S_AXIS:
#   ERROR: [BD 41-237] Bus Interface property FREQ_HZ does not match
# Control path
connect_bd_intf_net [get_bd_intf_pins ps_wizard_0/FPD_AXI_PL] [get_bd_intf_pins axi_smc/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M00_AXI] [get_bd_intf_pins $vrfdc/s_axi]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M01_AXI] [get_bd_intf_pins axi_dma_0/S_AXI_LITE]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M02_AXI] [get_bd_intf_pins axi_gpio_capture/S_AXI]

# External RF pins
connect_bd_intf_net [get_bd_intf_ports dac0_clk]      [get_bd_intf_pins $vrfdc/dac0_clk]
connect_bd_intf_net [get_bd_intf_ports adc3_clk]      [get_bd_intf_pins $vrfdc/adc3_clk]
connect_bd_intf_net [get_bd_intf_ports sysref_dac_in] [get_bd_intf_pins $vrfdc/sysref_dac_in]
connect_bd_intf_net [get_bd_intf_ports vout00]        [get_bd_intf_pins $vrfdc/vout00]
connect_bd_intf_net [get_bd_intf_ports vin30]         [get_bd_intf_pins $vrfdc/vin30]

# Datapath
connect_bd_intf_net [get_bd_intf_pins dac_tone_src_0/m_axis]      [get_bd_intf_pins $vrfdc/s00_axis]
connect_bd_intf_net [get_bd_intf_pins $vrfdc/m30_axis]            [get_bd_intf_pins adc_capture_gate_0/s_axis]
connect_bd_intf_net [get_bd_intf_pins adc_capture_gate_0/m_axis]  [get_bd_intf_pins cap_fifo/S_AXIS]
connect_bd_intf_net [get_bd_intf_pins cap_fifo/M_AXIS]            [get_bd_intf_pins cap_dwidth/S_AXIS]
connect_bd_intf_net [get_bd_intf_pins cap_dwidth/M_AXIS]          [get_bd_intf_pins axi_dma_0/S_AXIS_S2MM]
connect_bd_intf_net [get_bd_intf_pins axi_dma_0/M_AXI_S2MM]       [get_bd_intf_pins axi_noc_pl/S00_AXI]

# Step 12: Capture control and interrupts
connect_bd_net [get_bd_pins axi_gpio_capture/gpio_io_o]  [get_bd_pins adc_capture_gate_0/arm]
connect_bd_net [get_bd_pins adc_capture_gate_0/busy]     [get_bd_pins axi_gpio_capture/gpio2_io_i]

connect_bd_net [get_bd_pins axi_dma_0/s2mm_introut] [get_bd_pins ps_wizard_0/pl_ps_irq0]
connect_bd_net [get_bd_pins $vrfdc/irq]             [get_bd_pins ps_wizard_0/pl_ps_irq1]

set irq_tieoff [create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 irq_tieoff]
set_property -dict [list CONFIG.CONST_VAL {0} CONFIG.CONST_WIDTH {1}] $irq_tieoff
foreach idx {2 3 4 5 6 7 8 9 10 11 12 13 14 15} {
    connect_bd_net [get_bd_pins irq_tieoff/dout] [get_bd_pins ps_wizard_0/pl_ps_irq${idx}]
}

# Step 13: Addresses -- same 0xA400_0000 window and the same per-core
# assign/exclude dance base.tcl documents.
set pl_segments {
    {vrf_data_converter_0/s_axi/Reg  0xA4000000 0x00040000}
    {axi_dma_0/S_AXI_LITE/Reg        0xA4040000 0x00010000}
    {axi_gpio_capture/S_AXI/Reg      0xA4050000 0x00010000}
}

foreach seg $pl_segments {
    lassign $seg seg_path seg_offset seg_range
    foreach core {pmcps_0_psv_cortexa72_0 pmcps_0_psv_cortexa72_1 \
                   pmcps_0_psv_dpc_0 pmcps_0_psv_pmc_0} {
        assign_bd_address -offset $seg_offset -range $seg_range \
            -target_address_space [get_bd_addr_spaces ps_wizard_0/${core}] \
            [get_bd_addr_segs $seg_path] -force
    }
    foreach core {pmcps_0_psv_cortexr5_0 pmcps_0_psv_cortexr5_1 pmcps_0_psv_psm_0} {
        catch {exclude_bd_addr_seg \
            -target_address_space [get_bd_addr_spaces ps_wizard_0/${core}] \
            [get_bd_addr_segs $seg_path]}
    }
}

assign_bd_address -offset 0x00000000 -range 0x80000000 \
    -target_address_space [get_bd_addr_spaces axi_dma_0/Data_S2MM] \
    [get_bd_addr_segs axi_noc_ps/DDR_MC_PORTS/DDR_CH0_LEGACY] -force
assign_bd_address -offset 0x000800000000 -range 0x80000000 \
    -target_address_space [get_bd_addr_spaces axi_dma_0/Data_S2MM] \
    [get_bd_addr_segs axi_noc_ps/DDR_MC_PORTS/DDR_CH0_MED] -force

# Step 14: Validate and save
validate_bd_design
save_bd_design
